name: scholarly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase core (required for all Firebase services)
  firebase_core: ^3.0.0

  # Firebase Analytics (optional)
  firebase_analytics: ^11.0.0

  # Firebase Authentication (for login/signup)
  firebase_auth: ^5.1.0

  # Cloud Firestore (to store students' motivations or any other data)
  cloud_firestore: ^5.0.0

  # Cupertino icons (iOS style icons)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
